spring:
  application:
    name: ops-app2

server:
  port: 8081

app:
  profile: ${PROFILE:default}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true